In [ ]:
# Step 1: Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Step 2: Load the dataset
df = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\imblanced_dataset.csv")

In [4]:
df.head()

,customer_id,age,income,city,education,experience_years,employment_type,credit_score,loan_amount,default
0,101872,33.0,59985.0,Jaipur,Graduate,7.0,Salaried,790.0,NaN,No
1,100356,25.0,63499.0,Delhi,Postgraduate,4.0,Salaried,666.0,75592.0,No
2,101342,35.0,48128.0,Mumbai,Postgraduate,9.0,Business,689.0,36649.0,No
3,100910,57.0,109811.0,Mumbai,Graduate,31.0,Salaried,742.0,129423.0,No
4,101297,44.0,138290.0,Hyderabad,10th,17.0,Salaried,764.0,NaN,No

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2000 non-null   int64
 1   age               1954 non-null   float64
 2   income            1940 non-null   float64
 3   city              1965 non-null   str
 4   education         1970 non-null   str
 5   experience_years  1959 non-null   float64
 6   employment_type   1965 non-null   str
 7   credit_score      1945 non-null   float64
 8   loan_amount       1950 non-null   float64
 9   default           2000 non-null   str
dtypes: float64(5), int64(1), str(4)
memory usage: 156.4 KB

In [6]:
df.shape

(2000, 10)

### 1. Handling Missing Values

In [7]:
# Check missing values
df.isnull().sum()

customer_id          0
age                 46
income              60
city                35
education           30
experience_years    41
employment_type     35
credit_score        55
loan_amount         50
default              0
dtype: int64

In [ ]:
# Numerical columns
num_cols = df.select_dtypes(include=np.number).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
# Categorical columns
cat_cols = df.select_dtypes(include="object").columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21328\2416521011.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include="object").columns

In [10]:
df.isnull().sum()

customer_id         0
age                 0
income              0
city                0
education           0
experience_years    0
employment_type     0
credit_score        0
loan_amount         0
default             0
dtype: int64

### 2. Handle Outliers

In [ ]:
# Handle outliers using IQR
num_cols = ["age", "income", "experience_years", "credit_score", "loan_amount"]

for col in num_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    df[col] = df[col].clip(lower, upper)

In [12]:
df.describe()

,customer_id,age,income,experience_years,credit_score,loan_amount
count,2000.000000,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000
mean,100999.610000,35.700750,61976.7945,13.398250,698.087500,41785.592500
std,578.466548,9.540314,31798.4762,9.262177,64.654613,29264.836261
min,100001.000000,18.000000,10450.0000,0.000000,522.000000,1000.000000
25%,100498.750000,29.000000,37942.7500,6.000000,654.000000,20018.750000
50%,100998.500000,35.000000,54817.0000,13.000000,699.000000,35092.500000
75%,101501.250000,42.000000,78292.2500,19.000000,742.000000,56693.500000
max,102000.000000,61.500000,138816.5000,38.500000,874.000000,111705.625000

### 3. Handle Categorical Columns

In [13]:
# Categorical columns
df.select_dtypes(include="object").columns

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21328\2754935457.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['city', 'education', 'employment_type', 'default'], dtype='str')

In [14]:
# Remove Customer ID
df = df.drop("customer_id", axis=1)

In [15]:
# Convert the target column into numerical form
df["default"] = df["default"].map({"No": 0, "Yes": 1})

In [ ]:
# Handle categorical columns
df = pd.get_dummies(df,columns=["city", "education", "employment_type"],drop_first=True)

In [17]:
df.head()

,age,income,experience_years,credit_score,loan_amount,default,city_ Hyderabad,city_ Kolkata,city_ Mumbai,city_BANGALORE,...,education_12th,education_Diploma,education_GRADUATE,education_Graduate,education_Postgraduate,education_diploma,employment_type_Contract,employment_type_Salaried,employment_type_Self-Employed,employment_type_Unemployed
0,33.0,59985.0,7.0,790.0,35092.500,0,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
1,25.0,63499.0,4.0,666.0,75592.000,0,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
2,35.0,48128.0,9.0,689.0,36649.000,0,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,57.0,109811.0,31.0,742.0,111705.625,0,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
4,44.0,138290.0,17.0,764.0,35092.500,0,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 43 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            2000 non-null   float64
 1   income                         2000 non-null   float64
 2   experience_years               2000 non-null   float64
 3   credit_score                   2000 non-null   float64
 4   loan_amount                    2000 non-null   float64
 5   default                        2000 non-null   int64
 6   city_ Hyderabad                2000 non-null   bool
 7   city_ Kolkata                  2000 non-null   bool
 8   city_ Mumbai                   2000 non-null   bool
 9   city_BANGALORE                 2000 non-null   bool
 10  city_Bangalore                 2000 non-null   bool
 11  city_CHENNAI                   2000 non-null   bool
 12  city_Chennai                   2000 non-null   bool
 13  city_DELHI                     2000 non-null   bool
 14  city_Delhi                     2000 non-null   bool
 15  city_Hyderabad                 2000 non-null   bool
 16  city_JAIPUR                    2000 non-null   bool
 17  city_Jaipur                    2000 non-null   bool
 18  city_Kolkata                   2000 non-null   bool
 19  city_Mumbai                    2000 non-null   bool
 20  city_Pune                      2000 non-null   bool
 21  city_chennai                   2000 non-null   bool
 22  city_delhi                     2000 non-null   bool
 23  city_hyderabad                 2000 non-null   bool
 24  city_jaipur                    2000 non-null   bool
 25  city_kolkata                   2000 non-null   bool
 26  city_mumbai                    2000 non-null   bool
 27  city_pune                      2000 non-null   bool
 28  education_ 12th                2000 non-null   bool
 29  education_ Diploma             2000 non-null   bool
 30  education_ Graduate            2000 non-null   bool
 31  education_ Postgraduate        2000 non-null   bool
 32  education_10th                 2000 non-null   bool
 33  education_12th                 2000 non-null   bool
 34  education_Diploma              2000 non-null   bool
 35  education_GRADUATE             2000 non-null   bool
 36  education_Graduate             2000 non-null   bool
 37  education_Postgraduate         2000 non-null   bool
 38  education_diploma              2000 non-null   bool
 39  employment_type_Contract       2000 non-null   bool
 40  employment_type_Salaried       2000 non-null   bool
 41  employment_type_Self-Employed  2000 non-null   bool
 42  employment_type_Unemployed     2000 non-null   bool
dtypes: bool(37), float64(5), int64(1)
memory usage: 166.1 KB

In [19]:
# Divide the data into X and Y
X = df.drop("default", axis=1)
y = df["default"]

In [20]:
y.value_counts()

default
0    1802
1     198
Name: count, dtype: int64

In [21]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

### 4. Handle Scaling

In [22]:
# Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### 5. Handle Imbalanced Problem Using SMOTE

In [23]:
# Handle imbalance using SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled,y_train)

In [ ]:
print("Before SMOTE:")
print(y_train.value_counts())
print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

Before SMOTE:
default
0    1442
1     158
Name: count, dtype: int64

After SMOTE:
default
0    1442
1    1442
Name: count, dtype: int64

In [ ]:
# Ridge Classification
from sklearn.linear_model import RidgeClassifier
ridge = RidgeClassifier(alpha=1.0)
ridge_model = ridge.fit(X_train_smote,y_train_smote)
y_pred_ridge = ridge_model.predict(X_test_scaled)

In [ ]:
# Evaluation
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print("Ridge Classifier")
print("Accuracy:", accuracy_score(y_test, y_pred_ridge))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_ridge))

Ridge Classifier
Accuracy: 0.8475

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.84      0.91       360
           1       0.39      0.95      0.55        40

    accuracy                           0.85       400
   macro avg       0.69      0.89      0.73       400
weighted avg       0.93      0.85      0.87       400

In [ ]:
# Lasso Regression
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.01)
lasso_model = lasso.fit(X_train_smote,y_train_smote)
y_pred_lasso = lasso_model.predict(X_test_scaled)

In [ ]:
# Polynomial Features
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train_smote)
X_test_poly = poly.transform(X_test_scaled)

In [ ]:
# Polynomial Regression
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
poly_model = LR.fit(X_train_poly,y_train_smote)
y_pred_poly = poly_model.predict(X_test_poly)