In [3]:
# 1. Load the dataset and display the first 10 records.
import pandas as pd
df = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\Bank_customer_churn.csv")
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [4]:
# 2. Display the last 15 customers. 
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
# 3. Show 7 random customer records.
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4420,4421,15571261,Toscani,714,Germany,Female,35,6,126077.43,2,1,1,53954.24,0
1082,1083,15663438,Andrejew,688,Spain,Male,36,0,89772.30,1,1,0,177383.68,1
9287,9288,15609176,Cawthorne,688,France,Female,32,5,0.00,2,0,1,177607.77,0
524,525,15763274,Wu,661,France,Male,48,3,120320.54,1,0,0,96463.25,0
6632,6633,15779915,O'Loghlin,694,Spain,Male,31,5,0.00,1,1,0,35593.18,0
2114,2115,15746594,Wu,732,Spain,Male,33,8,0.00,1,1,0,119882.70,0
3597,3598,15671630,McMillan,796,Germany,Female,40,1,99745.95,1,1,0,177524.19,0

In [6]:
# 4. Print complete dataset information and identify:
# • Total columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [7]:
# 5. Find missing values in every column.
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
# 6. Display only numerical columns.
df.select_dtypes(include = ["int","float"])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [9]:
# 7. Generate the statistical summary of numerical columns.
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [10]:
# 8. Find duplicate rows and print how many exist.
df.duplicated().sum()

np.int64(0)

In [11]:
# 9. Remove duplicate rows and store the cleaned dataset.
df.drop_duplicates(inplace = True)

In [12]:
# 10. Count how many customers have exited and how many have not exited.
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [13]:
# 11. Rename the following columns:
# CustomerId → Customer_ID
# CreditScore → Credit_Score
# EstimatedSalary → Salary
# Exited → Churn
df.rename(columns={
    "CustomerId":"Customer_ID",
    "CreditScore":"Credit_Score",
    "EstimatedSalary":"Salary",
    "Exited":"Churn"
},inplace = True)
df.head()

,RowNumber,Customer_ID,Surname,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [14]:
# 12. Add the prefix Bank_ to every column name.
df = df.add_prefix("Bank_")
df.head()

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
# 13. Convert the Age column into float datatype.
df["Bank_Age"] = df["Bank_Age"].astype("float")
df.dtypes

Bank_RowNumber           int64
Bank_Customer_ID         int64
Bank_Surname            object
Bank_Credit_Score        int64
Bank_Geography          object
Bank_Gender             object
Bank_Age               float64
Bank_Tenure              int64
Bank_Balance           float64
Bank_NumOfProducts       int64
Bank_HasCrCard           int64
Bank_IsActiveMember      int64
Bank_Salary            float64
Bank_Churn               int64
dtype: object

In [16]:
# 14. Convert the Exited column into string datatype.
df["Bank_Churn"] = df["Bank_Churn"].astype("str")
df.dtypes

Bank_RowNumber           int64
Bank_Customer_ID         int64
Bank_Surname            object
Bank_Credit_Score        int64
Bank_Geography          object
Bank_Gender             object
Bank_Age               float64
Bank_Tenure              int64
Bank_Balance           float64
Bank_NumOfProducts       int64
Bank_HasCrCard           int64
Bank_IsActiveMember      int64
Bank_Salary            float64
Bank_Churn              object
dtype: object

In [17]:
# 15. Suppose the Balance column has missing values. Replace them using the mean of the Balance column.
df["Bank_Balance"] = df["Bank_Balance"].fillna(df["Bank_Balance"].mean())
df["Bank_Balance"]

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Bank_Balance, Length: 10000, dtype: float64

In [18]:
# 16. Suppose the Age column has missing values. Replace them using the median age.
df["Bank_Age"] = df["Bank_Age"].fillna(df["Bank_Age"].median())
df["Bank_Age"]

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Bank_Age, Length: 10000, dtype: float64

In [19]:
# 17. Display only the first five rows after renaming the columns.
df = df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Churn"
})
df.head()

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [20]:
# 18. Create a new DataFrame by dropping these columns: RowNumber, CustomerId, Surname Display the first 10 rows.
new_df = df.drop(columns=["Bank_RowNumber", "Bank_Customer_ID", "Bank_Surname"])
new_df.head(10)

,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50.0,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29.0,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44.0,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27.0,2,134603.88,1,1,1,71725.73,0

In [21]:
# 19. Drop the Geography column and display dataset information again.
df = df.drop(columns=["Bank_Geography"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Bank_RowNumber       10000 non-null  int64
 1   Bank_Customer_ID     10000 non-null  int64
 2   Bank_Surname         10000 non-null  object
 3   Bank_Credit_Score    10000 non-null  int64
 4   Bank_Gender          10000 non-null  object
 5   Bank_Age             10000 non-null  float64
 6   Bank_Tenure          10000 non-null  int64
 7   Bank_Balance         10000 non-null  float64
 8   Bank_NumOfProducts   10000 non-null  int64
 9   Bank_HasCrCard       10000 non-null  int64
 10  Bank_IsActiveMember  10000 non-null  int64
 11  Bank_Salary          10000 non-null  float64
 12  Bank_Churn           10000 non-null  object
dtypes: float64(3), int64(7), object(3)
memory usage: 1015.8+ KB

In [22]:
# 20. Rename NumOfProducts to Products and HasCrCard to CreditCard.
df = df.rename(columns={
    "Bank_NumOfProducts": "Products",
    "Bank_HasCrCard": "CreditCard"
})
df.head()

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Products,CreditCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [23]:
# 21. Your manager wants cleaner column names.
# Display the first five rows.
df = df.rename(columns={
    "Bank_RowNumber":"Row_No",
    "Bank_Customer_Id":"Customer_ID",
    "Bank_Surname":"Last_Name",
    "Bank_CreditScore":"Credit_Score",
    "Bank_Geography":"Country",
    "Bank_Gender":"Sex",
    "Bank_EstimatedSalary":"Salary",
    "Bank_Churn":"Target"
})
df.head()

,Row_No,Bank_Customer_ID,Last_Name,Bank_Credit_Score,Sex,Bank_Age,Bank_Tenure,Bank_Balance,Products,CreditCard,Bank_IsActiveMember,Bank_Salary,Target
0,1,15634602,Hargrave,619,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [24]:
# 22. Create a new DataFrame that contains only numeric columns. Then generate its statistical summary.
num_df = df.select_dtypes(include=["int", "float"])
num_df.describe()

,Row_No,Bank_Customer_ID,Bank_Credit_Score,Bank_Age,Bank_Tenure,Bank_Balance,Products,CreditCard,Bank_IsActiveMember,Bank_Salary
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000

In [25]:
# 23. Your company received duplicate customer records.
#Tasks:
# • Count duplicates.
df.duplicated().sum()

np.int64(0)

In [26]:
# • Remove duplicates.
df = df.drop_duplicates()

In [27]:
# • Display dataset information after cleaning.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Row_No               10000 non-null  int64
 1   Bank_Customer_ID     10000 non-null  int64
 2   Last_Name            10000 non-null  object
 3   Bank_Credit_Score    10000 non-null  int64
 4   Sex                  10000 non-null  object
 5   Bank_Age             10000 non-null  float64
 6   Bank_Tenure          10000 non-null  int64
 7   Bank_Balance         10000 non-null  float64
 8   Products             10000 non-null  int64
 9   CreditCard           10000 non-null  int64
 10  Bank_IsActiveMember  10000 non-null  int64
 11  Bank_Salary          10000 non-null  float64
 12  Target               10000 non-null  object
dtypes: float64(3), int64(7), object(3)
memory usage: 1015.8+ KB

In [28]:
# 24. Management wants every column name to begin with Customer_. Apply this transformation using the appropriate method.
df = df.add_prefix("Customer_")
df

,Customer_Row_No,Customer_Bank_Customer_ID,Customer_Last_Name,Customer_Bank_Credit_Score,Customer_Sex,Customer_Bank_Age,Customer_Bank_Tenure,Customer_Bank_Balance,Customer_Products,Customer_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Customer_Target
0,1,15634602,Hargrave,619,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [29]:
# 25. After renaming the columns, convert Age, Balance, Salary to float datatype. Print dataset information.
df = df.rename(columns={
    "Customer_Bank_Age": "Age",
    "Customer_Bank_Balance": "Balance",
    "Customer_Bank_Salary": "Salary"
})
df["Age"] = df["Age"].astype("float")
df["Balance"] = df["Balance"].astype("float")
df["Salary"] = df["Salary"].astype("float")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Customer_Row_No               10000 non-null  int64
 1   Customer_Bank_Customer_ID     10000 non-null  int64
 2   Customer_Last_Name            10000 non-null  object
 3   Customer_Bank_Credit_Score    10000 non-null  int64
 4   Customer_Sex                  10000 non-null  object
 5   Age                           10000 non-null  float64
 6   Customer_Bank_Tenure          10000 non-null  int64
 7   Balance                       10000 non-null  float64
 8   Customer_Products             10000 non-null  int64
 9   Customer_CreditCard           10000 non-null  int64
 10  Customer_Bank_IsActiveMember  10000 non-null  int64
 11  Salary                        10000 non-null  float64
 12  Customer_Target               10000 non-null  object
dtypes: float64(3), int64(7), object(3)
memory usage: 1015.8+ KB

In [30]:
# 26. Assume CreditScore contains missing values. Replace them with the median CreditScore.
df["Customer_Bank_Credit_Score"] = df["Customer_Bank_Credit_Score"].fillna(df["Customer_Bank_Credit_Score"].median())
df["Customer_Bank_Credit_Score"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: Customer_Bank_Credit_Score, Length: 10000, dtype: int64

In [31]:
# 27. Assume EstimatedSalary contains missing values. Replace them with the mean salary. Then print the first eight rows.
df.head(8)

,Customer_Row_No,Customer_Bank_Customer_ID,Customer_Last_Name,Customer_Bank_Credit_Score,Customer_Sex,Age,Customer_Bank_Tenure,Balance,Customer_Products,Customer_CreditCard,Customer_Bank_IsActiveMember,Salary,Customer_Target
0,1,15634602,Hargrave,619,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Male,44.0,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,Male,50.0,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Female,29.0,4,115046.74,4,1,0,119346.88,1

In [32]:
# 28. Perform all the following:
# • Remove duplicate rows.
# • Rename Exited to Target.
# • Convert Target to string.
# • Display dataset information.
df = df.drop_duplicates()
df = df.rename(columns={
    "Customer_Target": "Target"
})
df["Target"] = df["Target"].astype("str")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Customer_Row_No               10000 non-null  int64
 1   Customer_Bank_Customer_ID     10000 non-null  int64
 2   Customer_Last_Name            10000 non-null  object
 3   Customer_Bank_Credit_Score    10000 non-null  int64
 4   Customer_Sex                  10000 non-null  object
 5   Age                           10000 non-null  float64
 6   Customer_Bank_Tenure          10000 non-null  int64
 7   Balance                       10000 non-null  float64
 8   Customer_Products             10000 non-null  int64
 9   Customer_CreditCard           10000 non-null  int64
 10  Customer_Bank_IsActiveMember  10000 non-null  int64
 11  Salary                        10000 non-null  float64
 12  Target                        10000 non-null  object
dtypes: float64(3), int64(7), object(3)
memory usage: 1015.8+ KB

In [33]:
# 29. Create a copy of the dataset. Perform these transformations:
# • Rename Gender to CustomerGender
# • Rename Geography to Country
# • Add prefix Bank_
# • Remove RowNumber
# • Display first 10 rows
new_df = df.copy()
new_df.rename(columns = {
                       "Customer_Sex":"CustomerGender",
                       "Georaphy":"Country"
                      },inplace = True)
new_df = new_df.add_prefix("Bank_")
new_df.drop("RowNumber", axis=1, inplace=True)
head(10)

KeyError: "['RowNumber'] not found in axis"

In [34]:
# 30. Your manager asks you to prepare a cleaned dataset for the Machine Learning team. Perform all of these steps:
import pandas as pd
df = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\Bank_customer_churn.csv")
df.info()

df.isnull().sum()

df = df.drop_duplicates()

df = df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
})

df["Age"] = df["Age"].astype("float")
df["Balance"] = df["Balance"].astype("float")
df["Target"] = df["Target"].astype("str")

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

df = df.drop(columns=["RowNumber", "Surname"])

df.head(10)
df.describe()
df["Target"].value_counts(dropna = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     10000 non-null  int64
 1   Credit_Score    10000 non-null  int64
 2   Geography       10000 non-null  object
 3   Gender          10000 non-null  object
 4   Age             10000 non-null  float64
 5   Tenure          10000 non-null  int64
 6   Balance         10000 non-null  float64
 7   NumOfProducts   10000 non-null  int64
 8   HasCrCard       10000 non-null  int64
 9   IsActiveMember  10000 non-null  int64
 10  Salary          10000 non-null  float64
 11  Target          10000 non-null  object
dtypes: float64(3), int64(6), object(3)
memory usage: 937.6+ KB