In [4]:
import pandas as pd

In [6]:
# 1. Load the dataset using the appropriate Pandas method and store it in a variable named df.
df = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
# 2. Display the first 8 rows of the dataset.
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [8]:
# 3. Display the last 12 rows of the dataset.
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
# 4. Show 10 random rows from the dataset.
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1481,1482,15583748,McGuigan,592,Spain,Male,38,8,0.00,2,1,0,180426.20,0
3849,3850,15729836,Robinson,646,Spain,Male,32,1,0.00,2,1,0,183289.22,0
2511,2512,15693267,Dickson,679,Germany,Female,34,7,121063.85,1,1,0,56984.58,0
1480,1481,15716822,Moen,646,France,Male,30,5,98014.74,1,1,1,12757.14,0
5445,5446,15779174,Young,451,France,Female,36,2,0.00,2,1,1,180142.42,0
5797,5798,15775206,Hunter,699,France,Male,37,10,0.00,2,0,0,83263.04,0
2485,2486,15659501,Chioke,753,France,Female,38,6,142263.45,1,0,1,33730.43,0
4573,4574,15693906,Abbott,645,France,Female,24,3,34547.82,1,1,1,11638.17,0
1074,1075,15682618,Jamieson,535,France,Female,31,7,111855.04,2,1,1,36278.89,0
7467,7468,15803682,Angelo,651,Germany,Female,37,10,117791.06,2,1,1,75837.58,0

In [10]:
# 5. Find the shape of the dataset.
df.shape

(10000, 14)

In [11]:
# 6. Display complete information about the dataset using one method.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [13]:
# 7. Print the names of all columns in the dataset.
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [14]:
# 8. Find the data type of every column.
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [17]:
# 9. Check for missing values in every column using: isnull().sum(), isna().sum()
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [18]:
# 10.Select only one column:
df["CreditScore"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [20]:
# 11.Select the following multiple columns:
df[["CustomerId", "Surname", "Balance", "Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [21]:
# 12.Display only numeric columns using select_dtypes().
df.select_dtypes(include = ["number"])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [22]:
# 13.Generate the statistical summary of all numeric columns using describe().
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [23]:
# 14.Check for duplicate rows in the dataset.
# How many duplicate rows exist?
df.duplicated().sum()

np.int64(0)

In [26]:
# Remove all duplicate rows.
df.drop_duplicates(inplace=True)

In [28]:
# 15.Count the number of customers in each class of the Exited column using value_counts().
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [33]:
# 16. Take two numbers from user. Perform all arithmetic operations and also check which number is greater using comparison operators.
num1 = int(input("Enter First Number = "))
num2 = int(input("Enter Second Number = "))

print("Addition = ", num1+num2)
print("Substraction = ", num1-num2)
print("Multiplication = ", num1*num2)
print("Division = ", num1/num2)
print("floor Division = ", num1//num2)
print("Modulus = ", num1%num2)
print("Power = ", num1**num2)

if num1 > num2:
    print("Greatest Number is",num1)
elif num1 < num2:
    print("Greatest Number is" , num2)
else:
    print("Both Numbes are Equal")

Enter First Number =  9
Enter Second Number =  16

Addition =  25
Substraction =  -7
Multiplication =  144
Division =  0.5625
floor Division =  0
Modulus =  9
Power =  1853020188851841
Greatest Number is 16

In [34]:
# 17. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop completely when number 40 is reached using break.
for i in range(1,50):
    if i == 40:
        break

    if i % 5 == 0:
        continue
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

In [38]:
# 18. Take numbers from user until they enter negative number. Calculate sum and average using while loop.
sum = 0
count = 0
while True:
    num = int(input("Enter a Number = "))
    if num<0:
        break
    sum = sum+num
    count += 1

if count > 0:
    average = sum/count
    print("Total Sum = ", sum)
    print("Average = ", average)
else:
    print("Invalid Number")

Enter a Number =  6
Enter a Number =  9
Enter a Number =  10
Enter a Number =  7
Enter a Number =  2
Enter a Number =  -9

Total Sum =  34
Average =  6.8

In [40]:
# 19. Print the following pattern using nested loops:
for i in range(5,0,-1):
    for j in range(i):
        print("*", end="")
    print()

*****
****
***
**
*

In [41]:
# 20. Find the factorial of a number using for loop and also using while loop.
# Using For Loop
num = int(input("Enter a Number = "))
fact = 1
for i in range(1,num+1):
    fact = fact*i
print("Factorial = ", fact)

Enter a Number =  8

Factorial =  40320

In [42]:
# Using While Loop
num = int(input("Enter a Number = "))
fact = 1
n = 1
while n <= num:
    fact = fact*n
    n+=1
print("Factorial = ", fact)

Enter a Number =  5

Factorial =  120

In [45]:
# 21. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace spaces with -, and check if it starts with “Hello”.
text = input("Enter a Sentence = ")
print("Upper Case = ", text.upper())
print("Count of a = ", text.count("a"))
print("Rewrite the Sentence after replacing space by - =", text.replace(" ", "-"))
print("Start with 'Hello'", text.startswith("Hello"))

Enter a Sentence =  My name is Ayushi.

Upper Case =  MY NAME IS AYUSHI.
Count of a =  1
Rewrite the Sentence after replacing space by - = My-name-is-Ayushi.
Start with 'Hello' False

In [46]:
# 22. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending) and reverse.
numbers = [1, 2, 3, 4, 5, 6]
print("Original list = ", numbers)

# Append
numbers.append(7)
print(numbers)

# Insert
numbers.insert(2, 15)
print(numbers)

# Remove
numbers.remove(5)
print(numbers)

# POP
numbers.pop()
print(numbers)

# Sort(Descending)
numbers.sort(reverse=True)
print(numbers)

# Reverse
numbers.reverse()
print(numbers)

Original list =  [1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 15, 3, 4, 5, 6, 7]
[1, 2, 15, 3, 4, 6, 7]
[1, 2, 15, 3, 4, 6]
[15, 6, 4, 3, 2, 1]
[1, 2, 3, 4, 6, 15]

In [52]:
# 23. Create a dictionary of 4 students (name:marks). Print only those students who scored more than 80 using items().
students = {"Riya ":87, "Rahul":91, "Ayushi":77, "Shubhangi":80}
print("Student Scoring more than 80 marks")
for name, marks in students.items():
    if marks > 80:
        print(name, ":", marks)

Student Scoring more than 80 marks
Riya  : 87
Rahul : 91

In [61]:
# 24. Create two sets and perform union, intersection, difference. Also add and discard elements.
set1 = {10, 20, 30, 40}
set2 = {30, 40, 50, 60}

print("Set 1:", set1)
print("Set 2:", set2)

# Union
print(set1.union(set2))

# Intersection
print(set1.intersection(set2))

# Difference
print(set1.difference(set2))

# Add element
set1.add(70)
print(set1)

# Discard element
set1.discard(20)
print(set1)

Set 1: {40, 10, 20, 30}
Set 2: {40, 50, 60, 30}
{40, 10, 50, 20, 60, 30}
{40, 30}
{10, 20}
{70, 40, 10, 20, 30}
{70, 40, 10, 30}

In [60]:
# 25. Create a class Student with private attribute __marks. Add getter and setter with validation (0–100).
# Create class
class Student:
    def __init__(self):
        self.__marks = 0

     # Getter
    def get_marks(self):
        return self.__marks
        
    # Setter
    def set_marks(self, marks):
        if marks >= 0 and marks <= 100:
            self.__marks = marks
        else:
            print("Invalid Marks! Marks should be between 0 and 100.")

# object
s = Student()
marks = int(input("Enter Marks: "))
s.set_marks(marks)
print("Marks =", s.get_marks())

Enter Marks:  87

Marks = 87

In [64]:
# 26.  Create class BankAccount with private __balance. Add deposit and withdraw methods. Raise custom exception if balance becomes negative.
class NegativeBalanceError(Exception):
    pass

class BankAccount:
    def __init__(self,balance):
        self.__balance = balance

    # Deposit
    def deposit(self,amount):
        self._amount = amount
        balance = self.__balance + amount
        print("Amount Deposited = ", self._amount)

    # Withdraw
    def withdraw(self,amount):
        self._amount = amount
        if amount > self.__balance:
            raise NegativeBalanceError("Error : Insufficient Balance, Please try Again.")
        else:
            balance = self.__balance - amount
            print("Amount Withdraw = ", self._amount)

    # getter
    def get_balance(self):
        return self.__balance

# object
B = BankAccount(5000)

try:
    B.deposit(2000)
    B.withdraw(1000)
    B.withdraw(5000)

except NegativeBalanceError as e:
    print(e)
    
print("Current Balance = ", B.get_balance())

Amount Deposited =  2000
Amount Withdraw =  1000
Amount Withdraw =  5000
Current Balance =  5000

In [86]:
# 27. Create a class Employee with class attribute company_name. Show that it is shared by all objects. Also update the class attribute.
class Employee:

    company_name = "TCS"

    def __init__(self, name):
        self.name = name

    def display(self):
        print("Employee Name:", self.name)
        print("Company Name:", Employee.company_name)

e1 = Employee("Ayushi")
e2 = Employee("Rahul")

print("Before Updating Company Name")
e1.display()
e2.display()

Employee.company_name = "Infosys"

print("After Updating Company Name")
e1.display()
e2.display()

Before Updating Company Name
Employee Name: Ayushi
Company Name: TCS
Employee Name: Rahul
Company Name: TCS
After Updating Company Name
Employee Name: Ayushi
Company Name: Infosys
Employee Name: Rahul
Company Name: Infosys

In [96]:
# 28. Create class Product with private__price. And getter and setter. Setter should not allow price less tahn 100.
class Product:

    def __init__(self,price):
        self.__price = price
        price = 100
        
    # getter
    def get_price(self):
        return self.__price

    # setter
    def set_price(self, price):
        if price >= 100:
            self.__price = price
        else:
            print("Price should not be less than 100")
            
p = Product(0)

price = int(input("Enter Price: "))
p.set_price(price)

print("Price =", p.get_price())

Enter Price:  50

Price should not be less than 100
Price = 0

In [82]:
# 29. Create class Rectangle with private length and width. Add method to calculate area and perimeter.
class Rectangle:

    def __init__(self, length, width):
        self.__length = length
        self.__width = width

    # Method 
    def area(self):
        return self.__length * self.__width

    # Method
    def perimeter(self):
        return 2 * (self.__length + self.__width)

length = int(input("Enter Length: "))
width = int(input("Enter Width: "))

r = Rectangle(length, width)

print("Area =", r.area())
print("Perimeter =", r.perimeter())

Enter Length:  5
Enter Width:  8

Area = 40
Perimeter = 26

In [98]:
# 30. Create single level inheritance: Person → Student. Use super() in constructor.
class Person:

    def __init__(self, name, age):
        self.name = name
        self.age = age


class Student(Person):

    def __init__(self, name, age, roll_no):
        super().__init__(name, age)
        self.roll_no = roll_no

    def display(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Roll No:", self.roll_no)


s = Student("Ayushi", 21, 101)
s.display()

Name: Ayushi
Age: 21
Roll No: 101

In [99]:
# 31. Create multi-level inheritance: Person → Employee → Manager. Override a method at each level.
class Person:

    def show(self):
        print("I am a Person")


class Employee(Person):

    def show(self):
        print("I am an Employee")


class Manager(Employee):

    def show(self):
        print("I am a Manager")


m = Manager()
m.show()

I am a Manager

In [100]:
# 32. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound() method.
class Animal:

    def sound(self):
        print("Animal makes sound")


class Dog(Animal):

    def sound(self):
        print("Dog barks")


class Cat(Animal):

    def sound(self):
        print("Cat meows")


d = Dog()
c = Cat()

d.sound()
c.sound()

Dog barks
Cat meows

In [102]:
# 33. Create abstract class Shape with abstract method area(). Implement it in Circle and Square using super().
from abc import ABC, abstractmethod

class Shape(ABC):

    def __init__(self):
        print("Shape Constructor")

    @abstractmethod
    def area(self):
        pass

class Circle(Shape):

    def __init__(self, radius):
        super().__init__()
        self.radius = radius

    def area(self):
        print("Area of Circle =", 3.14 * self.radius * self.radius)

class Square(Shape):

    def __init__(self, side):
        super().__init__()
        self.side = side

    def area(self):
        print("Area of Square =", self.side * self.side)

c = Circle(5)
c.area()

s = Square(4)
s.area()

Shape Constructor
Area of Circle = 78.5
Shape Constructor
Area of Square = 16

In [103]:
# 34. Create multiple inheritance with two classes Father and Mother. Create child class and resolve method conflict.

# Parent class 1
class Father:

    def show(self):
        print("Father is a Doctor")
        
# Parent class 2
class Mother:

    def show(self):
        print("Mother is a Teacher")

# Child class
class Child(Father, Mother):

    def display(self):
        print("Child inherits from Father and Mother")

c = Child()

c.display()
Father.show(c)
Mother.show(c)

Child inherits from Father and Mother
Father is a Doctor
Mother is a Teacher

In [104]:
# 35. Create a class Calculator that can add 2 or 3 numbers (method overloading using *args).
class Calculator:

    def add(self, *num):
        sum = 0

        for i in num:
            sum = sum + i

        print("Addition =", sum)

c = Calculator()

c.add(10, 20)
c.add(10, 20, 30)

Addition = 30
Addition = 60

In [106]:
# 36. Create class Point and overload + and > operators.
class Point:

    def __init__(self, x):
        self.x = x

    # Overload + operator
    def __add__(self, other):
        return self.x + other.x

    # Overload > operator
    def __gt__(self, other):
        return self.x > other.x

p1 = Point(20)
p2 = Point(10)

print("Addition =", p1 + p2)

if p1 > p2:
    print("Point 1 is Greater")
else:
    print("Point 2 is Greater")

Addition = 30
Point 1 is Greater

In [109]:
# 37. Write a program that handles ZeroDivisionError, ValueError and IndexError using multiple except blocks.
list1 = [10, 20, 30]

try:
    num1 = int(input("Enter First Number: "))
    num2 = int(input("Enter Second Number: "))

    result = num1 / num2
    print("Division =", result)

    index = int(input("Enter Index: "))
    print("Element =", list1[index])

except ZeroDivisionError:
    print("Error : Cannot divide by zero.")

except ValueError:
    print("Error : Please enter valid integer values.")

except IndexError:
    print("Error : Index is out of range.")

Enter First Number:  20
Enter Second Number:  0

Error : Cannot divide by zero.

In [112]:
# 38. Create a custom exception InvalidAgeError. Raise it if age is less than 18.
class InvalidAgeError(Exception):
    pass

try:
    age = int(input("Enter Age: "))
    if age < 18:
        raise InvalidAgeError

    print("You are eligible.")

except InvalidAgeError:
    print("Error : Age should be 18 or above.")

except ValueError:
    print("Error : Please enter a valid age.")

Enter Age:  21

You are eligible.

In [113]:
# 39. Write a program to read a file, count number of words, and write the count into another file.
file1 = open("data.txt", "r")
data = file1.read()
file1.close()
words = data.split()
count = len(words)

file2 = open("count.txt", "w")
file2.write("Number of Words = " + str(count))
file2.close()
print("Number of Words =", count)

Number of Words = 1

In [114]:
# 40. Create a menu-driven program for file operations: Write, Read, Append, and Exit. Handle FileNotFoundError.
while True:

    print("\n----- MENU -----")
    print("1. Write")
    print("2. Read")
    print("3. Append")
    print("4. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:

        file = open("student.txt", "w")
        data = input("Enter Data: ")
        file.write(data)
        file.close()
        print("Data Written Successfully.")

    elif choice == 2:

        try:
            file = open("student.txt", "r")
            print(file.read())
            file.close()

        except FileNotFoundError:
            print("File Not Found.")

    elif choice == 3:

        try:
            file = open("student.txt", "a")
            data = input("Enter Data: ")
            file.write("\n" + data)
            file.close()
            print("Data Appended Successfully.")

        except FileNotFoundError:
            print("File Not Found.")

    elif choice == 4:

        print("Program Ended.")
        break

    else:
        print("Invalid Choice.")

----- MENU -----
1. Write
2. Read
3. Append
4. Exit

Enter your choice:  1
Enter Data:  Ayushi

Data Written Successfully.

----- MENU -----
1. Write
2. Read
3. Append
4. Exit

Enter your choice:  2

Ayushi

----- MENU -----
1. Write
2. Read
3. Append
4. Exit

Enter your choice:  3
Enter Data:  Gajbhiye

Data Appended Successfully.

----- MENU -----
1. Write
2. Read
3. Append
4. Exit

Enter your choice:  4

Program Ended.

In [118]:
# 41. Create a class Student with private marks list.
# • Setter should validate each mark (0-100)
# • Overload > operator to compare two students based on average
# • Raise custom exception if marks list is empty
class EmptyMarksError(Exception):
    pass

class Student:

    def __init__(self):
        self.__marks = []

    def set_marks(self, marks):

        if len(marks) == 0:
            raise EmptyMarksError("Marks list is empty")

        for i in marks:
            if i < 0 or i > 100:
                print("Invalid Marks")
                return

        self.__marks = marks

    def get_marks(self):
        return self.__marks

    def average(self):
        return sum(self.__marks) / len(self.__marks)

    def __gt__(self, other):
        return self.average() > other.average()


try:

    s1 = Student()
    s2 = Student()

    s1.set_marks([80, 90, 85])
    s2.set_marks([70, 75, 80])

    print("Student 1 Marks:", s1.get_marks())
    print("Student 2 Marks:", s2.get_marks())

    print("Average of Student 1:", s1.average())
    print("Average of Student 2:", s2.average())

    if s1 > s2:
        print("Student 1 has higher average")
    else:
        print("Student 2 has higher average")

except EmptyMarksError as e:
    print(e)

Student 1 Marks: [80, 90, 85]
Student 2 Marks: [70, 75, 80]

TypeError: 'int' object is not callable

In [120]:
# 42. Write a menu-driven banking system using OOP + File Handling. Store account details in a file. Handle FileNotFoundError, ValueError, and custom exceptions.
class InvalidAmountError(Exception):
    pass

class Bank:
    def deposit(self):
        try:
            amount = int(input("Enter Deposit Amount: "))

            if amount <= 0:
                raise InvalidAmountError

            file = open("bank.txt", "a")
            file.write("Deposit = " + str(amount) + "\n")
            file.close()
            print("Amount Deposited Successfully")

        except InvalidAmountError:
            print("Amount should be greater than 0")

        except ValueError:
            print("Enter Valid Amount")

    def display(self):
        try:
            file = open("bank.txt", "r")
            print(file.read())
            file.close()

        except FileNotFoundError:
            print("File Not Found")

b = Bank()

while True:
    print("\n1. Deposit")
    print("2. Display")
    print("3. Exit")

    choice = int(input("Enter Choice: "))
    if choice == 1:
        b.deposit()

    elif choice == 2:
        b.display()

    elif choice == 3:
        print("Thank You")
        break

    else:
        print("Invalid Choice")

1. Deposit
2. Display
3. Exit

Enter Choice:  1
Enter Deposit Amount:  2000

Amount Deposited Successfully

1. Deposit
2. Display
3. Exit

Enter Choice:  2

Deposit = 1500
Deposit = 2000


1. Deposit
2. Display
3. Exit

Enter Choice:  3

Thank You

In [121]:
# 43. Using dictionary + exception handling, create a student management system that can:
# • Add student
# • Update marks
# • Delete student
# • Display all Raise custom exception if student not found.
class StudentNotFoundError(Exception):
    pass

students = {}

while True:
    print("\n1. Add Student")
    print("2. Update Marks")
    print("3. Delete Student")
    print("4. Display Students")
    print("5. Exit")

    choice = int(input("Enter Choice: "))

    if choice == 1:
        name = input("Enter Student Name: ")
        marks = int(input("Enter Marks: "))
        students[name] = marks
        print("Student Added Successfully")

    elif choice == 2:
        try:
            name = input("Enter Student Name: ")
            if name not in students:
                raise StudentNotFoundError
            marks = int(input("Enter New Marks: "))
            students[name] = marks
            print("Marks Updated Successfully")

        except StudentNotFoundError:
            print("Student Not Found")

    elif choice == 3:
        try:
            name = input("Enter Student Name: ")
            if name not in students:
                raise StudentNotFoundError

            del students[name]
            print("Student Deleted Successfully")

        except StudentNotFoundError:
            print("Student Not Found")

    elif choice == 4:
        print("Student Records")
        for name, marks in students.items():
            print(name, ":", marks)

    elif choice == 5:
        print("Program Ended")
        break

    else:
        print("Invalid Choice")

1. Add Student
2. Update Marks
3. Delete Student
4. Display Students
5. Exit

Enter Choice:  1
Enter Student Name:  Rahul
Enter Marks:  89

Student Added Successfully

1. Add Student
2. Update Marks
3. Delete Student
4. Display Students
5. Exit

Enter Choice:  2
Enter Student Name:  Rahul
Enter New Marks:  91

Marks Updated Successfully

1. Add Student
2. Update Marks
3. Delete Student
4. Display Students
5. Exit

Enter Choice:  3
Enter Student Name:  Rahul

Student Deleted Successfully

1. Add Student
2. Update Marks
3. Delete Student
4. Display Students
5. Exit

Enter Choice:  4

Student Records

1. Add Student
2. Update Marks
3. Delete Student
4. Display Students
5. Exit

Enter Choice:  5

Program Ended

In [122]:
# 44. Create a class Employee with private salary.
# • Setter should not allow more than 15% increase at once
# • Keep history of all salary changes
# • Add static method to calculate tax
# • Overload > operator to compare employees by salary

class Employee:
    def __init__(self, salary):
        self.__salary = salary
        self.history = [salary]

    # Getter
    def get_salary(self):
        return self.__salary

    # Setter
    def set_salary(self, salary):
        increase = salary - self.__salary
        if increase > (self.__salary * 15 / 100):
            print("Salary increase cannot be more than 15%")
        else:
            self.__salary = salary
            self.history.append(salary)
            print("Salary Updated")

    # Salary
    def show_history(self):
        print("Salary History:", self.history)

    # Static Method
    @staticmethod
    def calculate_tax(salary):
        tax = salary * 10 / 100
        return tax

    # Operator Overloading
    def __gt__(self, other):
        return self.__salary > other.__salary


e1 = Employee(50000)
e2 = Employee(45000)

print("Employee 1 Salary:", e1.get_salary())
print("Employee 2 Salary:", e2.get_salary())

e1.set_salary(55000)
e1.show_history()
print("Tax =", Employee.calculate_tax(e1.get_salary()))

if e1 > e2:
    print("Employee 1 has higher salary")
else:
    print("Employee 2 has higher salary")

Employee 1 Salary: 50000
Employee 2 Salary: 45000
Salary Updated
Salary History: [50000, 55000]
Tax = 5500.0
Employee 1 has higher salary

In [123]:
# 45. Design a complete system combining:
# • Abstract class Vehicle
# • Multiple inheritance (Electric + Fuel)
# • Operator overloading (compare by speed)
# • Private attributes + getter/setter
# • Custom exceptions
# • File handling to save vehicle details
# • Duck Typing for start() method

from abc import ABC, abstractmethod

# Custom Exception
class InvalidSpeedError(Exception):
    pass

# Abstract Class
class Vehicle(ABC):

    @abstractmethod
    def display(self):
        pass

# Parent Class 1
class Electric:
    def charge(self):
        print("Charging Electric Vehicle")


# Parent Class 2
class Fuel:
    def fill(self):
        print("Filling Fuel")

# Child Class
class Car(Vehicle, Electric, Fuel):
    def __init__(self, name, speed):
        self.name = name
        self.__speed = 0
        self.set_speed(speed)

    # Getter
    def get_speed(self):
        return self.__speed

    # Setter
    def set_speed(self, speed):
        if speed < 0:
            raise InvalidSpeedError("Invalid Speed")
        self.__speed = speed

    # Abstract Method
    def display(self):
        print("Vehicle Name:", self.name)
        print("Speed:", self.__speed)

    # Operator Overloading
    def __gt__(self, other):
        return self.__speed > other.__speed


# Duck Typing Classes
class Bike:

    def start(self):
        print("Bike Started")

class Bus:

    def start(self):
        print("Bus Started")

def start_vehicle(vehicle):
    vehicle.start()

try:

    c1 = Car("Tesla", 180)
    c2 = Car("BMW", 160)

    c1.display()
    c1.charge()
    c1.fill()

    if c1 > c2:
        print("Tesla is Faster")
    else:
        print("BMW is Faster")

    file = open("vehicle.txt", "w")
    file.write(c1.name + " " + str(c1.get_speed()))
    file.close()

    b1 = Bike()
    b2 = Bus()

    start_vehicle(b1)
    start_vehicle(b2)

except InvalidSpeedError as e:
    print(e)

Vehicle Name: Tesla
Speed: 180
Charging Electric Vehicle
Filling Fuel
Tesla is Faster
Bike Started
Bus Started